# Generated by Django 5.0.1 on 2025-01-01 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('addressee_name', models.CharField(max_length=200)),
                ('address_lines', models.TextField()),
                ('postal_code', models.CharField(max_length=20)),
                ('city_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FlightSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_iata_code', models.CharField(max_length=10)),
                ('departure_terminal', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_iata_code', models.CharField(max_length=10)),
                ('arrival_terminal', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_time', models.DateTimeField()),
                ('carrier_code', models.CharField(max_length=10)),
                ('flight_number', models.CharField(max_length=20)),
                ('aircraft_code', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=50)),
                ('number_of_stops', models.IntegerField()),
                ('co2_emissions_weight', models.FloatField()),
                ('co2_emissions_unit', models.CharField(max_length=10)),
                ('cabin', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('total', models.FloatField()),
                ('base', models.FloatField()),
                ('refundable_taxes', models.FloatField()),
                ('grand_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('passport_number', models.CharField(max_length=50)),
                ('passport_expiry_date', models.DateField()),
                ('passport_issuance_country', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segments', models.ManyToManyField(to='amadeus_integration.flightsegment')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=50, unique=True)),
                ('reference', models.CharField(max_length=20)),
                ('creation_date', models.DateTimeField()),
                ('flight_offer_id', models.CharField(max_length=20)),
                ('ticketing_option', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('contacts', models.ManyToManyField(to='amadeus_integration.contact')),
                ('itineraries', models.ManyToManyField(to='amadeus_integration.itinerary')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amadeus_integration.price')),
                ('travelers', models.ManyToManyField(to='amadeus_integration.traveler')),
            ],
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='amadeus_integration.booking')),
            ],
        ),
    ]
