CITIES = [
    {'city': 'Berlin', 'country': 'Germany', 'code': 'BER'},
    {'city': 'Munich', 'country': 'Germany', 'code': 'MUC'},
    {'city': 'Frankfurt', 'country': 'Germany', 'code': 'FRA'},
    {'city': 'New York', 'country': 'USA', 'code': 'NYC'},
    {'city': 'Los Angeles', 'country': 'USA', 'code': 'LAX'},
    {'city': 'Chicago', 'country': 'USA', 'code': 'CHI'},
    {'city': 'Tokyo', 'country': 'Japan', 'code': 'TYO'},
    {'city': 'Kyoto', 'country': 'Japan', 'code': 'UKY'},
    {'city': 'Osaka', 'country': 'Japan', 'code': 'OSA'},
    {'city': 'Paris', 'country': 'France', 'code': 'PAR'},
    {'city': 'Lyon', 'country': 'France', 'code': 'LYS'},
    {'city': 'Marseille', 'country': 'France', 'code': 'MRS'},
    {'city': 'London', 'country': 'UK', 'code': 'LON'},
    {'city': 'Manchester', 'country': 'UK', 'code': 'MAN'},
    {'city': 'Liverpool', 'country': 'UK', 'code': 'LPL'},
    {'city': 'Barcelona', 'country': 'Spain', 'code': 'BCN'},
    {'city': 'Madrid', 'country': 'Spain', 'code': 'MAD'},
    {'city': 'Chennai', 'country': 'India', 'code': 'MAA'},
    {'city': 'Mumbai', 'country': 'India', 'code': 'BOM'},
    {'city': 'Delhi', 'country': 'India', 'code': 'DEL'},
    {'city': 'Bangalore', 'country': 'India', 'code': 'BLR'},
    {'city': 'Hyderabad', 'country': 'India', 'code': 'HYD'},
    {'city': 'Kolkata', 'country': 'India', 'code': 'CCU'},
    {'city': 'Pune', 'country': 'India', 'code': 'PNQ'},
    {'city': 'Ahmedabad', 'country': 'India', 'code': 'AMD'},
    {'city': 'Surat', 'country': 'India', 'code': 'STV'},
    {'city': 'Jaipur', 'country': 'India', 'code': 'JAI'},
    {'city': 'Lucknow', 'country': 'India', 'code': 'LKO'},
    {'city': 'Kanpur', 'country': 'India', 'code': 'KNU'},
    # ... more cities
]
